<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>CbExamples.MSTest</RootNamespace>
    <IsPackable>false</IsPackable>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.11.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.11.1" />
    <PackageReference Include="CloudBeat.Kit.MSTest" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Infra\" />
    <None Remove="Pages\" />
    <None Remove="Tests\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Infra\" />
    <Folder Include="Pages\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="chromedriver.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
